# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invehicle_digital_twin/v1/invehicle_digital_twin.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6invehicle_digital_twin/v1/invehicle_digital_twin.proto\x12\x16invehicle_digital_twin\"R\n\x0c\x45ndpointInfo\x12\x10\n\x08protocol\x18\x01 \x01(\t\x12\x12\n\noperations\x18\x02 \x03(\t\x12\x0b\n\x03uri\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t\"\x81\x01\n\x10\x45ntityAccessInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12>\n\x10\x65ndpointInfoList\x18\x04 \x03(\x0b\x32$.invehicle_digital_twin.EndpointInfo\"\x1d\n\x0f\x46indByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"V\n\x10\x46indByIdResponse\x12\x42\n\x10\x65ntityAccessInfo\x18\x01 \x01(\x0b\x32(.invehicle_digital_twin.EntityAccessInfo\"Y\n\x0fRegisterRequest\x12\x46\n\x14\x65ntityAccessInfoList\x18\x01 \x03(\x0b\x32(.invehicle_digital_twin.EntityAccessInfo\"\x12\n\x10RegisterResponse2\xd4\x01\n\x14InvehicleDigitalTwin\x12]\n\x08\x46indById\x12\'.invehicle_digital_twin.FindByIdRequest\x1a(.invehicle_digital_twin.FindByIdResponse\x12]\n\x08Register\x12\'.invehicle_digital_twin.RegisterRequest\x1a(.invehicle_digital_twin.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invehicle_digital_twin.v1.invehicle_digital_twin_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENDPOINTINFO']._serialized_start=82
  _globals['_ENDPOINTINFO']._serialized_end=164
  _globals['_ENTITYACCESSINFO']._serialized_start=167
  _globals['_ENTITYACCESSINFO']._serialized_end=296
  _globals['_FINDBYIDREQUEST']._serialized_start=298
  _globals['_FINDBYIDREQUEST']._serialized_end=327
  _globals['_FINDBYIDRESPONSE']._serialized_start=329
  _globals['_FINDBYIDRESPONSE']._serialized_end=415
  _globals['_REGISTERREQUEST']._serialized_start=417
  _globals['_REGISTERREQUEST']._serialized_end=506
  _globals['_REGISTERRESPONSE']._serialized_start=508
  _globals['_REGISTERRESPONSE']._serialized_end=526
  _globals['_INVEHICLEDIGITALTWIN']._serialized_start=529
  _globals['_INVEHICLEDIGITALTWIN']._serialized_end=741
# @@protoc_insertion_point(module_scope)
