# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: module/managed_subscribe/v1/managed_subscribe.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3module/managed_subscribe/v1/managed_subscribe.proto\x12\x11managed_subscribe\")\n\nConstraint\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"_\n\x17SubscriptionInfoRequest\x12\x10\n\x08\x65ntityId\x18\x01 \x01(\t\x12\x32\n\x0b\x63onstraints\x18\x02 \x03(\x0b\x32\x1d.managed_subscribe.Constraint\"J\n\x18SubscriptionInfoResponse\x12\x10\n\x08protocol\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\"1\n\x10SubscriptionInfo\x12\x10\n\x08protocol\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\"\xa5\x01\n\x0f\x43\x61llbackPayload\x12\x10\n\x08\x65ntityId\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x32\n\x0b\x63onstraints\x18\x03 \x03(\x0b\x32\x1d.managed_subscribe.Constraint\x12=\n\x10subscriptionInfo\x18\x04 \x01(\x0b\x32#.managed_subscribe.SubscriptionInfo\"]\n\x16TopicManagementRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x33\n\x07payload\x18\x02 \x01(\x0b\x32\".managed_subscribe.CallbackPayload\"\x19\n\x17TopicManagementResponse2\x82\x01\n\x10ManagedSubscribe\x12n\n\x13GetSubscriptionInfo\x12*.managed_subscribe.SubscriptionInfoRequest\x1a+.managed_subscribe.SubscriptionInfoResponse2\x86\x01\n\x18ManagedSubscribeCallback\x12j\n\x11TopicManagementCB\x12).managed_subscribe.TopicManagementRequest\x1a*.managed_subscribe.TopicManagementResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'module.managed_subscribe.v1.managed_subscribe_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONSTRAINT']._serialized_start=74
  _globals['_CONSTRAINT']._serialized_end=115
  _globals['_SUBSCRIPTIONINFOREQUEST']._serialized_start=117
  _globals['_SUBSCRIPTIONINFOREQUEST']._serialized_end=212
  _globals['_SUBSCRIPTIONINFORESPONSE']._serialized_start=214
  _globals['_SUBSCRIPTIONINFORESPONSE']._serialized_end=288
  _globals['_SUBSCRIPTIONINFO']._serialized_start=290
  _globals['_SUBSCRIPTIONINFO']._serialized_end=339
  _globals['_CALLBACKPAYLOAD']._serialized_start=342
  _globals['_CALLBACKPAYLOAD']._serialized_end=507
  _globals['_TOPICMANAGEMENTREQUEST']._serialized_start=509
  _globals['_TOPICMANAGEMENTREQUEST']._serialized_end=602
  _globals['_TOPICMANAGEMENTRESPONSE']._serialized_start=604
  _globals['_TOPICMANAGEMENTRESPONSE']._serialized_end=629
  _globals['_MANAGEDSUBSCRIBE']._serialized_start=632
  _globals['_MANAGEDSUBSCRIBE']._serialized_end=762
  _globals['_MANAGEDSUBSCRIBECALLBACK']._serialized_start=765
  _globals['_MANAGEDSUBSCRIBECALLBACK']._serialized_end=899
# @@protoc_insertion_point(module_scope)
